name = "FuncType"
uuid = "c0c4d893-2c42-4991-9340-5cf81baef85d"
authors = ["chengchingwen <adgjl5645@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"

[compat]
ExprTools = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
